name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build-all:ci
    - run: yarn docs

    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.1.0
      with:
        email: essmale2005@gmail.com
        build_dir: docs
        branch: gh-pages
